SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;


INSERT INTO `idols` (`id`, `eName`, `jName`, `age`, `height`, `weight`, `birthday`, `bloodType`, `bwh`, `hobbies`, `writingHand`, `horoscope`, `hometown`, `type`, `cv`, `profilePic`, `puchiPic`) VALUES
(1, 'Uzuki Shimamura', '島村卯月', '17', '159', '45', 'April 24', 'O', '83/59/87', 'Long Phone Calls with friends', 'Right', 'Taurus', 'Tokyo', 'Cute', 'Ayaka Ohashi', 'uzuki1.png', 'uzuki2.png'),
(2, 'Rin Shibuya', '渋谷凜', '15', '165', '44', 'August 10', 'B', '80/56/81', 'Dog Walking', 'Right', 'Leo', 'Tokyo', 'Cool', 'Ayaka Fukuhara', 'rin1.png', 'rin2.png'),
(3, 'Mio Honda', '本田未央', '15', '161', '46', 'December 1', 'B', '84/58/87', 'Shopping', 'Right', 'Sagittarius', 'Chiba', 'Passion', 'Sayuri Hara', 'mio1.png', 'mio2.png'),
(4, 'Airi Totoki', '十時愛梨', '18', '161', '46', 'December 8', 'O', '88/58/88', 'Baking Cakes', 'Right', 'Sagittarius', 'Akita', 'Passion', 'Hitomi Harada', 'airi1.png', 'airi2.png'),
(5, 'Miria Akagi', '赤城みりあ', '11', '140', '36', 'April 14', 'AB', '75/55/78', 'Chatting', 'Left', 'Aries', 'Tokyo', 'Passion', 'Tomoyo Kurosawa', 'miria1.png', 'miria2.png'),
(6, 'Mika Jougasaki', '城ヶ崎美嘉', '17', '162', '43', 'November 12', 'AB', '80/56/82', 'Karaoke', 'Left', 'Scorpio', 'Saitama', 'Passion', 'Haruka Yoshimura', 'mika1.png', 'mika2.png'),
(7, 'Kirari Moroboshi', ' 諸星きらり', '17', '182', '60', 'September 1', 'O', '91/64/86', 'Collecting Cute Things', 'Right', 'Virgo', 'Tokyo', 'Passion', 'Rei Matsuzaki', 'kirari1.png', 'kirari2.png'),
(8, 'Shiki Ichinose', '一ノ瀬志希', '18', '161', '43', 'May 30', 'O', '83/57/82', 'Observation, Suspicious Scientific Experiments, Disappearance ', 'Right', 'Gemini', 'Iwate', 'Cute', 'Kotomi Aihara', 'shiki1.png', 'shiki2.png'),
(9, 'Kanako Mimura', '三村かな子', '17', '153', '52', 'January 6', 'O', '90/65/89', 'Making Sweets', 'Right', 'Capricorn', 'Tokyo', 'Cute', 'Yuka Ohtsubo', 'kanako1.png', 'kanako2.png'),
(10, 'Frederica Miyamoto', '宮本フレデリカ', '19', '164', '46', 'February 14', 'B', '83/57/85', 'Fashion', 'Left', 'Aquarius', 'Paris', 'Cute', 'Asami Takano', 'frederica1.png', 'frederica2.png'),
(11, 'Anzu Futaba', '双葉杏', '17', '139', '30', 'September 2', 'B', '?/?/?', 'None', 'Right', 'Tender Virgo', 'Hokkaido', 'Cute', 'Hiromi Igarashi', 'anzu1.png', 'anzu2.png'),
(12, 'Minami Nitta', '新田美波', '19', '165', '45', 'July 27', 'O', '82/55/85', 'Lacrosse, Qualifying', 'Right', 'Leo', 'Hiroshima', 'Cool', 'Aya Suzaki', 'minami1.png', 'minami2.png'),
(13, 'Ranko Kanzaki', '神崎蘭子 ', '14', '156', '41', 'April 8', 'A', '81/57/80', 'Drawing', 'Right', 'Aries', 'Kumamoto', 'Cool', 'Maaya Uchida', 'ranko1.png', 'ranko2.png'),
(14, 'Karen Hojo', '北条加蓮', '16', '155', '42', 'September 5', 'B', '83/55/81', 'Nail art', 'Right', 'Virgo', 'Tokyo', 'Cool', 'Mai Fuchigami', 'karen1.png', 'karen2.png'),
(15, 'Anastasia', 'アナスタシア', '15', '165', '43', 'September 19', 'O', '80/54/80', 'House parties, stargazing', 'Both', 'Virgo', 'Hokkaido', 'Cool', 'Sumire Uesaka', 'anastasia1.png', 'anastasia2.png'),
(16, 'Nao Kamiya', '神谷奈緒', '17', '154', '44', 'September 16', 'AB', '83/58/81', 'Watching anime', 'Left', 'Virgo', 'Chiba', 'Cool', 'Eriko Matsui', 'nao1.png', 'nao2.png'),
(17, 'Chieri Ogata', '緒方智絵里', '16', '153', '42', 'June 11', 'A', '79/57/80', 'Collecting four-leaf clovers', 'Right', 'Gemini', 'Mie', 'Cute', 'Naomi Oozora', 'chieri1.png', 'chieri2.png'),
(18, 'Nana Abe', '安部菜々', 'Eternally 17', '146', '40', 'May 15', 'O', '84/57/84', 'Communicating with Planet Usamin', 'Right', 'Taurus', 'Planet Usamin', 'Cute', 'Marie Miyake', 'nana1.png', 'nana2.png'),
(19, 'Miho Kohinata', '小日向美穂', '17', '155', '42', 'December 16', 'O', '82/59/86', 'Basking in the sun', 'Left', 'Sagittarius', 'Kumamoto', 'Cute', 'Minami Tsuda', 'miho1.png', 'miho2.png'),
(20, 'Sae Kobayakawa', '小早川紗枝', '15', '148', '42', 'October 18', 'AB', '78/56/80', 'Traditional Japanese dancing', 'Right', 'Libra', 'Kyoto', 'Cute', 'Rika Tachibana', 'sae1.png', 'sae2.png'),
(21, 'Sachiko Koshimizu', '輿水幸子', '14', '142', '37', 'November 25', 'B', '74/52/75', 'Making copies of study notes', 'Left', 'Sagittarius', 'Yamanashi', 'Cute', 'Ayana Taketatsu', 'sachiko1.png', 'sachiko2.png'),
(22, 'Saori Okuyama', '奥山沙織', '19', '156', '47', 'June 12', 'B', '83/57/81', 'Reading', 'Right', 'Gemini', 'Akita', 'Cute', 'N/A', 'saori1.png', 'saori2.png'),
(23, 'Yukari Mizumoto', '水本ゆかり', '15', '155', '42', 'October 18', 'A', '81/56/82', 'Flute', 'Right', 'Libra', 'Aoyama', 'Cute', 'Akane Fujita', 'yukari1.png', 'yukari2.png'),
(24, 'Yuka Nakano', '中野有香', '18', '149', '40', 'March 23', 'B', '77/57/81', 'Karate', 'Right', 'Aries', 'Kagawa', 'Cute', 'Shino Shimoji', 'yuka1.png', 'yuka2.png'),
(25, 'Noriko Shiina', '椎名法子', '13', '147', '38', 'October 10', 'O', '76/55/79', 'Tasting New Donuts', 'Right', 'Libra', 'Osaka', 'Cute', 'Chiyo Tomaru', 'noriko1.png', 'noriko2.png'),
(26, 'Rina Fujimoto', '藤本里奈', '18', '154', '41', 'October 14', 'A', '77/55/80', 'Riding motorcycles, browsing at convenience stores', 'Right', 'Libra', 'Shonan', 'Cute', 'Mayumi Kaneko', 'rina1.png', 'rina2.png'),
(27, 'Karin Domyoji', '道明寺歌鈴', '17', '155', '43', 'January 1', 'A', '80/55/83', 'Cleaning the temple grounds', 'Right', 'Capricorn', 'Nara', 'Cute', 'Hiyori Nitta', 'karin1.png', 'karin2.png'),
(28, 'Mai Fukuyama', '福山舞', '10', '132', '28', 'January 21', 'O', '64/56/70', 'Unicycling', 'Left', 'Aquarius', 'Hyogo', 'Cute', 'N/A', 'mai1.png', 'mai2.png'),
(29, 'Azuki Momoi', '桃井あずき', '15', '145', '40', 'July 7', 'A', '80/55/78', 'Goldfish Scooping', 'Right', 'Cancer', 'Nagano', 'Cute', 'N/A', 'azuki1.png', 'azuki2.png'),
(30, 'Mayu Sakuma', '佐久間まゆ', '17', '153', '40', 'September 7', 'B', '78/54/80', 'Cooking, Knitting', 'Both', 'Virgo', 'Sendai', 'Cute', 'Yui Makino', 'mayu1.png', 'mayu2.png'),
(31, 'Kyoko Igarashi', '五十嵐響子', '15', '154', '43', 'August 10', 'AB', '81/57/80', 'General Housework', 'Left', 'Leo', 'Tottori', 'Cute', 'Atsumi Tanezaki', 'kyoko1.png', 'kyoko2.png'),
(32, 'Kotoka Saionji', '西園寺琴歌', '17', '156', '46', 'January 23', 'O', '87/57/85', 'Pressing Flowers', 'Right', 'Aquarius', 'Tokyo', 'Cute', 'N/A', 'kotoka1.png', 'kotoka2.png'),
(33, 'Clarice', 'クラリス', '20', '166', '45', 'August 26', 'AB', '80/55/82', 'Volunteering', 'Right', 'Virgo', 'Hyogo', 'Cute', 'N/A', 'clarice1.png', 'clarice2.png'),
(34, 'Chika Yokoyama', '横山千佳', '9', '127', '31', 'April 14', 'A', '60/55/65', 'Pretending to be a magical girl', 'Right', 'Capricorn', 'Miyazaki', 'Cute', 'N/A', 'chika1.png', 'chika2.png'),
(35, 'Shinobu Kudo', '工藤忍', '16', '154', '41', 'March 9', 'A', '78/54/81', 'Collecting Omake', 'Left', 'Pisces', 'Aomori', 'Cute', 'N/A', 'shinobu1.png', 'shinobu2.png'),
(36, 'Hotaru Shiragiku', '白菊ほたる', '13', '156', '42', 'April 19', 'AB', '77/53/79', 'Smile Practice, Idol Lessons', 'Left', 'Aries', 'Tottori', 'Cute', 'N/A', 'hotaru1.png', 'hotaru2.png'),
(37, 'Momoka Sakurai', '櫻井桃華', '12', '145', '39', 'April 8', 'A', '72/53/75', 'Teatime', 'Right', 'Aries', 'Kobe', 'Cute', 'Haruka Terui', 'momoka1.png', 'momoka2.png'),
(38, 'Rena Hyodo', '兵藤レナ', '27', '167', '48', 'October 3', 'O', '92/56/84', 'Playing Cards', 'Left', 'Libra', 'Tokyo', 'Cute', 'N/A', 'rena1.png', 'rena2.png'),
(39, 'Setsuna Imura', '井村雪菜', '17', '163', '48', 'August 27', 'AB', '85/60/88', 'Small collection of make-up', 'Right', 'Virgo', 'Akita', 'Cute', 'N/A', 'setsuna1.png', 'setsuna2.png'),
(40, 'Miyo Harada', '原田美世', '20', '163', '46', 'November 14', 'O', '86/59/85', 'Tinkering with cars and bikes', 'Right', 'Scorpio', 'Ishikawa', 'Cute', 'N/A', 'miyo1.png', 'miyo2.png'),
(41, 'Kana Imai', '今井加奈', '16', '153', '41', 'March 3', 'O', '81/56/79', 'Talking to Friends', 'Right', 'Pisces', 'Kouchi', 'Cute', 'N/A', 'kana1.png', 'kana2.png'),
(42, 'Mirei Hayasaka', '早坂美玲', '14', '147', '39', 'May 9', 'B', '75/54/77', 'Collecting stuffed toys', 'Right', 'Taurus', 'Miyagi', 'Cute', 'N/A', 'mirei1.png', 'mirei2.png'),
(43, 'Atsumi Munakata', '棟方愛海', '14', '151', '41', 'August 1', 'A', '73/56/75', 'Finger Exercises', 'Both', 'Leo', 'Aomori', 'Cute', 'N/A', 'atsumi1.png', 'atsumi2.png'),
(44, 'Riina Tada', '多田李衣菜', '17', '152', '41', 'June 30', 'A', '80/55/81', 'Listening to music', 'Right', 'Cancer', 'Tokyo', 'Cool', 'Ruriko Aoki', 'riina1.png', 'riina2.png'),
(45, 'Kaede Takagaki', '高垣楓', '25', '171', '49', 'June 14', 'AB', '81/57/83', 'Onsen excursions', 'Left', 'Gemini', 'Wakayama', 'Cool', 'Saori Hayami', 'kaede1.png', 'kaede2.png'),
(46, 'Koume Shirasaka', '白坂小梅', '13', '142', '34', 'March 28', 'AB', '65/50/70', 'Watching horror movies, visiting haunted places', 'Left', 'Aries', 'Hyogo', 'Cool', 'Chiyo Ousaki', 'koume1.png', 'koume2.png'),
(47, 'Kanade Hayami', '速水奏', '17', '162', '43', 'July 1', 'O', '86/55/84', 'Watching movies', 'Right', 'Cancer', 'Tokyo', 'Cool', 'Yuuko Iida', 'kanade1.png', 'kanade2.png'),
(48, 'Syuko Shiomi', '塩見周子', '18', '163', '45', 'December 12', 'B', '82/56/81', 'Darts, blood donation', 'Right', 'Sagittarius', 'Kyoto', 'Cool', 'Ru Thing', 'syuko1.png', 'syuko2.png'),
(49, 'Arisu Tachibana', '橘ありす', '12', '141', '34', 'July 31', 'B', '68/52/67', 'Games, reading (mystery)', 'Right', 'Aries', 'Hyogo', 'Cool', 'Amina Satou', 'arisu1.png', 'arisu2.png'),
(50, 'Haruna Kamijo', '上条春菜', '18', '156', '42', 'April 10', 'O', '79/56/80', 'Napping with her cat in the balcony', 'Right', 'Aries', 'Shizuoka', 'Cool', 'Mina Nagajima', 'haruna1.png', 'haruna2.png'),
(51, 'Yukimi Sajo', '佐城雪美', '10', '137', '30', 'September 28', 'AB', '63/47/65', 'Talking to her pet (black cat)', 'Right', 'Libra', 'Kyoto', 'Cool', 'N/A', 'yukimi1.png', 'yukimi2.png'),
(52, 'Chie Sasaki', '佐々木千枝', '11', '139', '33', 'June 7', 'A', '73/49/73', 'Sewing', 'Left', 'Gemini', 'Toyama', 'Cool', 'Asaka Imai', 'chie1.png', 'chie2.png'),
(53, 'Chinatsu Aikawa', '相川千夏', '23', '161', '43', 'November 11', 'B', '82/56/85', 'Reading at cafes', 'Right', 'Scorpio', 'Hokkaido', 'Cool', 'N/A', 'chinatsu1.png', 'chinatsu2.png'),
(54, 'Hina Araki', '荒木比奈', '20', '157', '43', 'April 9', 'A', '83/57/82', 'Drawing Manga', 'Right', 'Aries', 'Kanagawa', 'Cool', 'N/A', 'hina1.png', 'hina2.png'),
(55, 'Mizuki Kawashima', '川島瑞樹', '28', '159', '46', 'November 25', 'A', '87/57/85', 'Cleaning, Laundry', 'Right', 'Sagittarius', 'Osaka', 'Cool', 'Nao Touyama', 'mizuki1.png', 'mizuki2.png'),
(56, 'Sarina Matsumoto', '松本沙理奈', '22', '165', '48', 'September 1', 'A', '92/58/85', 'Shopping', 'Right', 'Virgo', 'Tokyo', 'Cool', 'N/A', 'sarina1.png', 'sarina2.png'),
(57, 'Ayase Honoka', '綾瀬穂乃香', '17', '161', '46', 'May 29', 'A', '85/57/84', 'Ballet', 'Right', 'Gemini', 'Miyagi', 'Cool', 'N/A', 'ayase1.png', 'ayase2.png'),
(58, 'Ryo Matsunaga', '松永涼', '18', '160', '47', 'October 1', 'AB', '90/56/86', 'Horror Movie Appreciation', 'Right', 'Libra', 'Tokyo', 'Cool', 'Haruka Chisuga ', 'ryo1.png', 'ryo2.png'),
(59, 'Fumika Sagisawa', '鷺沢文香', '19', '162', '45', 'October 27', 'AB', '84/54/81', 'Going to Bookstores, Making Bookmarks', 'Right', 'Scorpio', 'Nagano', 'Cool', 'MAO', 'fumika1.png', 'fumika2.png'),
(60, 'Asuka Ninomiya', '二宮飛鳥', '14', '154', '42', 'February 3', 'B', '75/55/78', 'Hair arrangement, Listening to the Radio, Drawing manga', 'Right', 'Aquarius', 'Shizuoka', 'Cool', 'Shiki Aoki', 'asuka1.png', 'asuka2.png'),
(61, 'Tamami Wakiyama', '脇山珠美', '16', '145', '38', 'September 20', 'B', '72/53/75', ' Kendo, Reading Historical Novels ', 'Right', 'Virgo', 'Saga', 'Cool', 'Misa Kayama', 'tamami1.png', 'tamami2.png'),
(62, 'Chiaki Kurokawa', '黒川千秋', '20', '163', '45', 'February 26', 'B', '86/57/86', 'Classic arts appreciation', 'Right', 'Pisces', 'Hokkaido', 'Cool', 'N/A', 'chiaki1.png', 'chiaki2.png'),
(63, 'Nono Morikubo', '森久保乃々', '14', '149', '38', 'August 27', 'AB', '73/55/76', 'Writing poems, collecting shoujo manga', 'Right', 'Virgo', 'Kanagawa', 'Cool', 'N/A', 'nono1.png', 'nono2.png'),
(64, 'Miyu Mifune', '三船美優', '26', '165', '46', 'February 25', 'AB', '85/60/85', 'Aromatherapy', 'Right', 'Pisces', 'Iwate', 'Cool', 'N/A', 'miyu1.png', 'miyu2.png'),
(65, 'Aki Yamato', '大和亜季', '21', '165', '51', 'December 16', 'O', '92/60/85', 'Survival Games, Collecting Plastic Models', 'Left', 'Sagittarius', 'Fukuoka', 'Cool', 'Tomo Muranaka', 'aki1.png', 'aki2.png'),
(66, 'Makino Yagami', '八神マキノ', '18', '160', '45', 'November 7', 'B', '85/56/83', 'Espionage', 'Right', 'Scorpio', 'Gifu', 'Cool', 'N/A', 'makino1.png', 'makino2.png'),
(67, 'Fujiwara Hajime', '藤原肇', '16', '161', '43', 'June 15', 'B', '80/55/84', 'Pottery, Fishing', 'Both', 'Gemini', 'Okayama', 'Cool', 'N/A', 'fujiwara1.png', 'fujiwara2.png'),
(68, 'Yuuki Haru', '結城晴', '12', '140', '37', 'July 17', 'A', '74/55/78', 'Soccer', 'Right', 'Cancer', 'Ehime', 'Cool', 'N/A', 'yuuki1.png', 'yuuki2.png'),
(69, 'Layla', 'ライラ', '16', '150', '40', 'May 21', 'O', '75/54/78', 'Chatting with strangers in the park', 'Right', 'Gemini', 'Dubai', 'Cool', 'N/A', 'layla1.png', 'layla2.png'),
(70, 'Yasuha Okazaki', '岡崎泰葉', '16', '153', '43', 'July 16', 'A', '79/55/80', 'Making Dollhouses', 'Left', 'Cancer', 'Nagasaki', 'Cool', 'N/A', 'yasuha1.png', 'yasuha2.png'),
(71, 'Seira Mizuki', '水木聖來', '23', '155', '43', 'April 27', 'B', '82/55/80', 'Dog Walking', 'Right', 'Taurus', 'Ibaraki', 'Cool', 'N/A', 'seira1.png', 'seira2.png'),
(72, 'Izumi Ohishi', '大石泉', '15', '157', '41', 'November 11', 'A', '83/55/82', 'Programming', 'Right', 'Scorpio', 'Shizuoka', 'Cool', 'N/A', 'izumi1.png', 'izumi2.png'),
(73, 'Tomo Fuji', '藤居朋', '19', '163', '45', 'July 1', 'O', '78/57/83', ' Fortune-telling', 'Right', 'Cancer', 'Shiga', 'Cool', 'N/A', 'tomo1.png', 'tomo2.png'),
(74, 'Rika Jougasaki', '城ヶ崎莉嘉', '12', '149', '36', 'July 30', 'B', '72/54/75', 'Collecting Stickers', 'Left', 'Leo', 'Saitama', 'Passion', 'Nozomi Yamamoto', 'rika1.png', 'rika2.png'),
(75, 'Yuki Himekawa', '姫川友紀', '20', '161', '44', 'September 14', 'B', '80/57/80', 'Watching baseball games', 'Right', 'Virgo', 'Miyazaki', 'Passion', 'Mako Morino', 'yuki1.png', 'yuki2.png'),
(76, 'Akane Hino', '日野茜', '17', '148', '40', 'August 4', 'AB', '80/60/82', 'Watching Rugby', 'Right', 'Leo', 'Tochigi', 'Passion', 'Chinatsu Akasaki', 'akane1.png', 'akane2.png'),
(77, 'Takamori Aiko', '高森藍子', '16', '155', '42', 'July 25', 'O', '74/60/79', 'Walking in the neighbourhood park', 'Right', 'Leo', 'Tokyo', 'Passion', 'Yuuki Kaneko', 'takamori1.png', 'takamori2.png'),
(78, 'Syoko Hoshi', '星輝子', '15', '142', '35', 'June 6', 'B', '73/53/75', 'Cultivating Mushrooms', 'Left', 'Gemini', 'Fukushima', 'Passion', 'Satsumi Matsuda', 'syoko1.png', 'syoko2.png'),
(79, 'Natsuki Kimura', '木村夏樹', '18', '159', '41', 'August 19', 'AB', '82/57/83', 'Touring', 'Left', 'Leo', 'Ibaraki', 'Passion', 'Kiyono Yasuno', 'natsuki1.png', 'natsuki2.png'),
(80, 'Yuko Hori', '堀裕子', '16', '157', '36', 'March 13', 'AB', '81/58/80', 'Psychic training', 'Left', 'Pisces', 'Fukui', 'Passion', 'Eri Suzuki', 'yuko1.png', 'yuko2.png'),
(81, 'Yui Ohtsuki', '大槻唯', '17', '155', '42', 'May 7', 'B', '84/56/83', 'Karaoke', 'Left', 'Taurus', 'Saitama', 'Passion', 'Nanami Yamashita', 'yui1.png', 'yui2.png'),
(82, 'Sanae Katagiri', '片桐早苗', '28', '152', '47', 'March 7', 'O', '92/58/84', 'Massages, large bathhouses', 'Right', 'Pisces', 'Niigata', 'Passion', 'Azumi Waki', 'sanae1.png', 'sanae2.png'),
(83, 'Natalia', 'ナターリア', '14', '155', '43', 'June 29', 'A', '84/55/86', 'Belly Dancing', 'Right', 'Cancer', 'Rio de Janeiro', 'Passion', 'N/A', 'natalia1.png', 'natalia2.png'),
(84, 'Kaoru Ryuzaki', '龍崎薫', '9', '132', '32', 'July 20', 'O', '65/51/70', 'Cooking', 'Right', 'Cancer', 'Ehime', 'Passion', 'Natsumi Haruse', 'kaoru1.png', 'kaoru2.png'),
(85, 'Aiba Yumi', '相葉夕美', '18', '158', '42', 'April 15', 'O', '81/57/80', 'Gardening', 'Right', 'Aries', 'Kanagawa', 'Passion', 'Juri Kimura', 'aiba1.png', 'aiba2.png'),
(86, 'Tomoka Wakabayashi', '若林智香', '17', '156', '45', 'March 7', 'A', '82/57/83', 'Cheerleading', 'Right', 'Virgo', 'Kagoshima', 'Passion', 'N/A', 'tomoka1.png', 'tomoka2.png'),
(87, 'Shizuku Oikawa', '及川雫', '16', '170', '56', 'June 3', 'O', '105/64/92', 'Milking, Driving tractors', 'Both', 'Gemini', 'Iwate', 'Passion', 'Yuri Noguchi', 'shizuku1.png', 'shizuku2.png'),
(88, 'Ayame Hamaguchi', '浜口あやめ', '15', '154', '42', 'January 13', 'A', '78/55/80', 'Watching historical plays, collecting ninja goods, touring film studios', 'Left', 'Capricorn', 'Mie', 'Passion', 'Masumi Tazawa', 'ayame1.png', 'ayame2.png'),
(89, 'Kumiko Matsuyama', '松山久美子', '21', '161', '44', 'January 21', 'A', '81/56/81', 'Piano', 'Right', 'Aquarius', 'Kanagawa', 'Passion', 'N/A', 'kumiko1.png', 'kumiko2.png'),
(90, 'Mary Cochran', 'メアリ・コクラン', '11', '152', '41', 'January 19', 'B', '71/59/73', 'Beauty routines, Gourmet tours', 'Left', 'Capricorn', 'San Francisco', 'Passion', 'N/A', 'mary1.png', 'mary2.png'),
(91, 'Miu Yaguchi', '矢口美羽', '14', '150', '41', 'July 10', 'B', '81/56/80', 'E-mail', 'Right', 'Cancer', 'Chiba', 'Passion', 'N/A', 'miu1.png', 'miu2.png'),
(92, 'Nina Ichihara', '市原仁奈', '9', '128', '29', 'February 8', 'B', '61/57/67', 'Collecting Kigurumi', 'Left', 'Aquarius', 'Shizuoka', 'Passion', 'Misaki Kuno', 'nina1.png', 'nina2.png'),
(93, 'Ema Senzaki', '仙崎恵磨', '21', '156', '45', 'June 27', 'O', '81/55/81', 'Collecting Leather Accessories', 'Left', 'Cancer', 'Osaka', 'Passion', 'N/A', 'ema1.png', 'ema2.png'),
(94, 'Takumi Mukai', '向井拓海', '18', '163', '53', 'August 7', 'A', '95/60/87', 'Bike tinkering', 'Right', 'Leo', 'Kanagawa', 'Passion', 'Yuuko Hara', 'takumi1.png', 'takumi2.png'),
(95, 'Hinako Kita', '喜多日菜子', '15', '158', '38', 'April 6', 'AB', '78/56/78', 'Having Delusions', 'Right', 'Aries', 'Akita', 'Passion', 'N/A', 'hinako1.png', 'hinako2.png'),
(96, 'Yuzu Kitami', '喜多見柚', '15', '156', '43', 'December 2', 'B', '82/57/82', 'Badminton', 'Left', 'Sagittarius', 'Saitama', 'Passion', 'N/A', 'yuzu1.png', 'yuzu2.png'),
(97, 'Tomoe Murakami', '村上巴', '13', '146', '37', 'January 3', 'A', '74/53/76', 'Enka, Shogi', 'Right', 'Capricorn', 'Hiroshima', 'Passion', 'N/A', 'tomoe1.png', 'tomoe2.png'),
(98, 'Yoshino Yorita', '依田芳乃', '16', '151', '40', 'July 3', 'O', '73/53/73', 'Resolving troubles, Collecting stones, Finding lost items', 'Right', 'Cancer', 'Kagoshima', 'Passion', 'N/A', 'yoshino1.png', 'yoshino2.png'),
(99, 'Emi Namba', '難波笑美', '17', '158', '45', 'May 1', 'O', '82/56/80', 'Live Comedy, Imitation', 'Right', 'Taurus', 'Osaka', 'Passion', 'Arisa Date', 'emi1.png', 'emi2.png'),
(100, 'Reina Koseki', '小関麗奈', '13', '148', '36', 'April 14', 'B', '75/50/77', 'Pranks', 'Left', 'Aries', 'Yamagata', 'Passion', 'N/A', 'reina1.png', 'reina2.png'),
(101, 'Risa Matoba', '的場梨沙', '12', '143', '38', 'November 19', 'B', '71/58/73', 'Dancing, Dates with Daddy', 'Right', 'Scorpio', 'Yamaguchi', 'Passion', 'N/A', 'risa1.png', 'risa2.png');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
